### ISSUE TITLE
Script returning values

### ISSUE THREAD

**Issue by markusmoenig** [ceronman/loxido#2]
Hi,

great implementation!

Would it be difficult to add the ability of scripts to return values ? For example if I would like to evaluate an expression and would expect an boolean return type, or if I want to evaluate a number expression and would expect a number to be returned ?

Thanks

**Comment by ceronman** [comment]
Hi @markusmoenig , you mean when using scripts from another language? I don't fully understand the question.

**Comment by markusmoenig** [comment]
Hi, no, I mean let's say I want to evaluate a script, for example "4 != 2" and want to check the return value of the script. I think right now scripts do not return a value right ? At least not the lox version of the book.
